version: "3.8"
services:
  # NOTE: exposed ports are for debug purposes only. Volume mounts are for both debug and logging. 
  fsw:
    image: "cfs-dev"
    command: "./core-cpu2"
    environment:
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.3
    build:
      context: .
      dockerfile: cfs.Dockerfile
      target: cfs-dev
      args:
        - USER_UID=${UID:-1000}
  rosgsw:
    image: "rosgsw-dev"
    command: "./run_rosgsw.sh"
    env_file:
      - env.sh
    build:
      context: .
      dockerfile: rosgsw.Dockerfile
      target: rosgsw-dev
      args:
        - USER_UID=${UID:-1000}
    environment:
      - ROS_DOMAIN_ID=2
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
  rosfsw:
    image: "rosfsw-dev"
    command: "./run_rosfsw.sh"
    env_file:
      - env.sh
    environment:
      - ROS_DOMAIN_ID=4
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      spaceip:
        ipv4_address: 10.5.0.5
        
  ros_base:
    image: "ros-base"
    build:
      context: .
      dockerfile: ros_base.Dockerfile
      target: ros-base
      args:
        - USER_UID=${UID:-1000}      

networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
