services:

  rosws:
    image: "jaxa-testing"
    environment:
      - ROS_DOMAIN_ID=2
      - DISPLAY=novnc:0.0      
    command: bash -c "sleep infinity"
#    env_file:
#      - env.sh
    networks:
      spaceip:
        ipv4_address: 10.5.0.2          
    build:
      context: .
      dockerfile: jaxa_jammy_testing.Dockerfile
      target: jaxa-testing
      args:
        - USER_UID=${UID:-1000}      
    volumes:
      - "./rosws:/root/code/rosws"
      - "./cfs:/root/code/cfs"
      - "./racs2_bridge:/root/code/racs2_bridge"
      
    working_dir: /root/code/rosws
    
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      spaceip:
        ipv4_address: 10.5.0.5
        

# NOTE: networks apparently can't be imported from related file?
networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

      
        
      
