version: "3.0"
services:
  # NOTE: exposed ports are for debug purposes only. Volume mounts are for both debug and logging. 
  fsw:
    image: "cfs-base"
    volumes:
      - ".:/shared"
    working_dir: /shared/cFS/build/exe/cpu2
    command: "./core-cpu2"
    # privileged is needed to avoid issues with mqueues. Running as non-root user may be an alternative
    privileged: true
    ports:
      - 1234:1234
      - 1235:1235
    networks:
      spaceip:
        ipv4_address: 10.5.0.3
    build:
      context: .
      dockerfile: cfs-Dockerfile
  rosgsw:
    image: "brash-ros"
    command: "./run_rosgsw.sh"
    volumes:
      - ".:/shared"
    working_dir: /shared/brash
    env_file:
      - env.sh
    build:
      # TODO: This Dockerfile is incomplete. Dev workflows may want to build manually.
      context: .
      dockerfile: ros-base-Dockerfile
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
  rosfsw:
    image: "brash-ros"
    command: "./run_rosfsw.sh"
    volumes:
      - ".:/shared"
    working_dir: /shared/brash
    env_file:
      - env.sh
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
