version: "3.8"
services:
  # NOTE: exposed ports are for debug purposes only. Volume mounts are for both debug and logging. 
  fsw:
    image: "brash-fsw-dev"
    command: ./core-cpu2
    volumes:
      - ./code/cFS:/code/cFS
    user: brash_user
    working_dir: /code/cFS/build/exe/cpu2
    environment:
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.3
    build:
      context: .
      dockerfile: brash_fsw.Dockerfile
      target: brash-fsw-dev
      args:
        - USER_UID=${UID:-1000}

  rosgsw:
    image: "brash-rosgsw-dev"
    command: sleep infinity
    volumes:
      - ./code/brash:/code/brash
      - ./code/cFS:/code/cFS
      - ./code/juicer:/code/juicer
#    env_file:
#      - env.sh
    environment:
      - ROS_DOMAIN_ID=2
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
    build:
      context: .
      dockerfile: brash_rosgsw.Dockerfile
      target: brash-rosgsw-dev
      args:
        - USER_UID=${UID:-1000}
        
  rosfsw:
    image: "brash-rosfsw-dev"
    command: sleep infinity
#    env_file:
#      - env.sh
    volumes:
      - ./code/brash:/code/brash
    environment:
      - ROS_DOMAIN_ID=4
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
    build:
      context: .
      dockerfile: brash_rosfsw.Dockerfile
      target: brash-rosfsw-dev
      args:
        - USER_UID=${UID:-1000}
        
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      spaceip:
        ipv4_address: 10.5.0.5

networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
         
         
  
