version: "3.8"
services:
  # NOTE: exposed ports are for debug purposes only. Volume mounts are for both debug and logging. 
  fsw:
    image: "brash-fsw"
    command: tail -f /dev/null
    volumes:
      - ".:/code"
    working_dir: /code/cFS/build/exe/cpu2
    
    environment:
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.3

  rosgsw:
    image: "brash-rosgsw"
    command: tail -f /dev/null
    env_file:
      - env.sh
    environment:
      - ROS_DOMAIN_ID=2
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.2
  rosfsw:
    image: "brash-rosfsw"
    command: tail -f /dev/null
    env_file:
      - env.sh
    environment:
      - ROS_DOMAIN_ID=4
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.4
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      spaceip:
        ipv4_address: 10.5.0.5

networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
         
         
  
